version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TimeX
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
